# This file contains values from Cookiecutter

default_context:
  project_name: "conversation-clustering"
  project_description: "`conversation-clustering` is a Python cli/package"
  organization: "CCU"
  license: "MIT"
  minimal_python_version: 3.11
  github_name: "elacosse"
  email: "eric.lacosse@mailbox.org"
  version: "0.1.0"
  line_length: "120"
  create_example_template: "none"
